### ISSUE TITLE
Proposal: flag to ignore recommendation step

### ISSUE THREAD

**Issue by jacopofar** [rustprooflabs/pgosm-flex#229]
Trying to import a pbf file already on my computer using the `--input-file` flag I found a bug in the way the path is handled. 

If I use an input file that is not in the output folder `/app/output` then the code ignores the complete path and assumes is in the output folder. The problem is in the [call to basepath](https://github.com/rustprooflabs/pgosm-flex/blob/208d31b11a477669a3c407136697d730986543aa/docker/osm2pgsql_recommendation.py#L82), the function above for example handles the absolute path correctly and can calculate the size of the file.

This probably can be fixed by "reattaching" the path in the command, but I think in general it would be useful to add a flag to ignore the recommendation and go with default values or provided ones. The use of the service requires to be able to connect to the service (but when importing a file that is on my disk I can run everything with the `--network=none`, and in case of company networks the service may not be reachable), and that the service itself will be available and work as intended (which also means to trust that is not compromised, or it will send command to execute verbatim).

Does it make sense to you?

**Comment by rustprooflabs** [comment]
There is no longer a requirement for an active internet connection. Version 0.4.0 was the last version that required a network for that recommendation API call, v0.4.1 and newer imports the recommendation package in Python (#195).

Regarding the use of `--input-file`, that option needs more documentation, I'll work on improving that.  The expectation is you link the path to your data from your host machine to `/app/output` in the docker container. I don't see why an absolute path at that stage would be wanted/needed.  The path containing the data file needs to be set at the `docker run` stage (right?), link the host path to the directory with your data file (`/your/path/to/wherever`) to the `/app/output` path inside the container.

```bash
docker run --name pgosm -d --rm    -v /your/path/to/wherever:/app/output    \
    -v /etc/localtime:/etc/localtime:ro -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD     -p 5433:5432 -d \
    rustprooflabs/pgosm-flex
```

With the custom path linked to the standard in-docker location, the `docker exec` step only needs the filename (or relative path for subdirectories) e.g. `--input-file=my-custom-file.osm.pbf`.

```bash
docker exec -it \
    pgosm python3 docker/pgosm_flex.py \
    --ram=8 \
    --region=north-america/us \
    --subregion=district-of-columbia \
   --input-file=my-custom-file.osm.pbf
```

That said -- the current path handling is messy. The root cause stems from osm2pgsql-tuner, I need to remove the lazy hard coded path I put in there -- https://github.com/rustprooflabs/osm2pgsql-tuner/issues/21.  Making that interface more flexible should enable using absolute path for `--input-path`.  Even though I'm not sure it's necessary, it shouldn't be broken!

**Comment by rustprooflabs** [comment]
The issue with absolute paths for `--input-file` should be fixed with #232 in the dev branch.  This is available now in the `dev` docker image with hash `6f7049ed72ae`.

**Comment by rustprooflabs** [comment]
@jacopofar At this time I don't like the idea of adding an option to bypass the osm2pgsql command recommendation. The issues identified above as justification have been resolved, so I do not see benefits beyond testing purposes.

The biggest downside I see to adding this option is adding an option for an override makes things more confusing for new users.  I don't want folks looking at the list of options and getting distracted trying to understand the osm2pgsql command and how and when to use `--slim` `--drop` `--cache` or `--flat-nodes`.  That's one of my personal favorite parts of this process in Docker is that I don't have to think at all about what command is used!

Another downside is the `--append` support coming in the next version will create a dependency between the osm2pgsql command and downstream logic.  If we allow custom override for the main command the replication command would need an option to override too.

For users that require more explicit control over the exact operation they may need to use the [manual process](https://github.com/rustprooflabs/pgosm-flex/blob/main/docs/MANUAL-STEPS-RUN.md).

**Comment by jacopofar** [comment]
Okay, no big deal. I think the changes above are enough for my use case. Thanks for your time!
